# Generated by Django 5.2.4 on 2025-07-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='contect',
            new_name='contact',
        ),
    ]
